
services:
  backend:
    build: .
    container_name: cont-serloc-back
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@172.16.238.10:5432/siclr_db
    networks:
      - database_network

networks:
  database_network:
    external: true
    name: database_network