
services:
  backend:
    build: .
    container_name: cont-serloc-back
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - database_network

networks:
  database_network:
    external: true
    name: database_network